# -*- coding: utf-8 -*-
"""Cleaning Data For Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mtUCJJT9GB0o-Fo2U7BWKLHCr3t9fXB3
"""

from google.colab import drive
import pandas as pd
import numpy as np
#import formatting tools
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Data_For_Collab/Crime_Data_from_2020_to_Present.csv'
df = pd.read_csv(file_path)

df.head()

df.columns

df = df[(df['date_reported'] >= '2022-01-01') & (df['date_reported'] < '2023-01-01')].copy()

columns_to_drop = ['division_number', 'date_occurred','reporting_district', 'part', 'crime_code','modus_operandi', 'premise_code','weapon_code',
       'weapon_description', 'status', 'crime_code_1',
       'crime_code_2', 'crime_code_3', 'crime_code_4', 'cross_street', 'latitude', 'longitude', ]
df = df.drop(columns=columns_to_drop)

df.head()

df['THEFT OF IDENTITY'] = df['crime_description'].apply(lambda x: 1 if x == 'THEFT OF IDENTITY' else 0)

df.head()

columns_to_convert = ['area_name']

# Iterate through each column and create binary columns
for column in columns_to_convert:
    binary_columns = pd.get_dummies(df[column])
    binary_columns = binary_columns.astype(int)
    df = pd.concat([df, binary_columns], axis=1)

pd.set_option('display.max_columns', None)
df.head()

df = df.select_dtnumeric_columns_df = df.select_dtypes(include='number')

df.head()

